baseURL = "https://utechjapan.net/"
languageCode = "en-us"
title = "UTechLab"
theme = "toha"
defaultContentLanguage = "en"
enableRobotsTXT = true
buildDrafts = true
buildFuture = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  tagline = "Innovating Technology"  # Toha uses 'tagline' instead of 'subtitle'
  description = "UTechLabs - Exploring Technology and Innovations"
  logo = "images/logo.png"
  favicon = "images/favicon.ico"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/post/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 4

[assets]
  disableFingerprinting = true

[module]
  [[module.imports]]
    path = "github.com/hugo-toha/toha/v4"
